[build]
  # This will be run the site build
  command = "webpack && nodemon server-build.js"
  # This is the directory is publishing to netlify's CDN
  publish = "webpack && nodemon server-build.js"
  # functions build directory
  # functions = "functions-build"